In [10]:
import numpy as np
import pandas as pd
import scipy.stats as st

<img src="https://i.ibb.co/93sNcdhp/Logo-pmat-color.png" align="right" width="150">

<br>

# **Intervalos de confianza para la Proporción**

## **Objetivos de aprendizaje**

- Comprender el concepto de **proporción poblacional** y su estimación a partir de una muestra.
- Calcular **intervalos de confianza (IC)** para una proporción con el enfoque normal aproximado.
- Interpretar el nivel de confianza y el margen de error en contextos reales.
- Analizar cómo influyen el tamaño de muestra y el nivel de confianza en la precisión de la estimación.

In [1]:
# @title
%%html
<div style="border: 4px solid #006d77; border-radius: 0px; overflow: hidden; font-family: sans-serif; max-width: 800px; margin-bottom: 20px;">

  <div style="background-color: #000000; color: #ffc107; padding: 10px 15px; font-weight: bold; font-size: 16px; display: flex; align-items: center;">
    <span style="margin-right: 10px; font-size: 18px;">💡</span>
    <span>Intervalos de confianza para la media y la proporción</span>
  </div>

  <div style="background-color: #ffffff; padding: 20px; display: flex; align-items: center; justify-content: space-between;">

    <div style="color: #000000; flex: 1; padding-right: 30px; font-size: 14px; line-height: 1.5;">
      ¿Sabes cuándo estimar un promedio y cuándo una tasa de éxito?
      <b>Escanea o haz clic sobre el código QR</b> para aprender a diferenciar y construir intervalos de confianza,
      ya sea para la media de una variable o la proporción de una categoría.
      </div>

    <div style="flex-shrink: 0;">
      <a href="https://duoc.h5p.com/content/1292748480894628278" target="_blank">
        <img src="https://i.ibb.co/hJf9LxSs/IC-media-y-p.png"
             alt="QR Code"
             style="width: 100px; height: 100px; border: none;">
      </a>
    </div>

  </div>

  <div style="background-color: #000000; color: #ffc107; padding: 8px 15px; font-weight: bold; font-size: 16px;">
    Presentación interactiva H5P
  </div>

</div>


## **Recordatorio clave**

- **Estimador de la proporción:**$\hspace{0.5 cm}$  $\hat{p} = \frac{x}{n}$,
  donde $x$ es el número de éxitos y $n$ el tamaño de la muestra.

- **Error estándar:** $\hspace{0.5 cm}$ $SE = \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}$

- **Intervalo de confianza para la proporción:** $\hspace{0.5 cm}$ $IC = \hat{p} \pm z_{\alpha/2} \cdot SE$

<br>
<br>

### **Comprobando condiciones antes de calcular IC**

Antes de aplicar las fórmulas anteriores, verifica estas 2 condiciones obligatorias en tus datos:

1.  **¿La muestra es aleatoria?**
    * Debe ser representativa del contexto del problema.
2.  **¿Hay suficientes éxitos y fracasos?** (Condición de Normalidad)
    * Calcula $n \cdot \hat{p}$ (debe ser $\geq 5$)
    * Calcula $n \cdot (1-\hat{p})$ (debe ser $\geq 5$)

*Si ambas respuestas son "SÍ", puedes proceder con el cálculo.*

# **Actividad 1 — Servidores estables en un centro de datos**

En un centro de datos que soporta múltiples aplicaciones críticas, la estabilidad de los servidores es esencial para garantizar disponibilidad y continuidad de servicio. Durante una semana de monitoreo se revisaron 200 servidores, registrando si experimentaron reinicios inesperados que podrían implicar caídas momentáneas o pérdida de datos. En total, se detectaron 26 servidores con incidentes de inestabilidad. El equipo de infraestructura necesita estimar cuál es la proporción real de servidores que podrían presentar este tipo de problemas para priorizar acciones de mantenimiento preventivo y asignar recursos de forma eficiente.

1. Calcula la proporción muestral $\hat{p}$ de servidores inestables.

In [7]:
x = 26
n = 200
p_muestra = x/n

print(f"La proporción muestral es {p_muestra:.0%}")

La proporción muestral es 13%


2. ¿Es posible comprobar que es posible utilizar una aproximación normal?

In [9]:
casos_exito = n * p_muestra >= 5 # Casos de exitos minimos
casos_fracaso = n * (1 - p_muestra) >= 5 # Casos de fracaso

if casos_exito & casos_fracaso:
    print("""
          Se cumplen las condiciones de éxito y fracaso mínimas.
          Entonces la muestra es válida para hablar de una aproximación normal.
    """)
else:
    print("No se cumplen las condiciones")
    


          Se cumplen las condiciones de éxito y fracaso mínimas.
          Entonces la muestra es válida para hablar de una aproximación normal.
    


2. Construye un IC al 95% para la proporción poblacional.  


In [25]:
alfa = 0.05
z = st.norm.ppf(1 - alfa/2)
SE = np.sqrt(p_muestra * (1 - p_muestra)/n)
IC = (p_muestra - z * SE, p_muestra + z * SE)
print(f"IC 95% = [ {IC[0]:.4f} ; {IC[1]:.4f} ]")

IC 95% = [ 0.0834 ; 0.1766 ]


3. Interpreta el resultado para el equipo técnico.

**Basado en el IC, en el mejor de los casos el 8,34% de los servidores va a fallar, mientras que en el peor de los casos el 17,66% de los servidores va a fallar, al 95% de confianza**

# **Actividad 2 — Tasa de aprobación de un examen en educación**

En una asignatura clave de una carrera en educación superior, aprobar los exámenes iniciales es fundamental para medir el aprendizaje y orientar apoyos tempranos. En la primera evaluación participaron 120 estudiantes, de los cuales 72 aprobaron. El equipo docente quiere estimar la proporción real de estudiantes que aprueban este tipo de evaluaciones para tomar decisiones sobre reforzamientos y ajustar la planificación de la asignatura.

1. Calcula $ \hat{p}$ y construye un intervalo de confianza del 95% para la proporción poblacional. Imprime los resultados en representación decimal y porcentual.

In [27]:
n = 120
x = 72
p_muestra = x/n

alfa = 0.05
z = st.norm.ppf(1 - alfa/2)
SE = np.sqrt(p_muestra * (1 - p_muestra)/n)
IC = (p_muestra - z * SE, p_muestra + z * SE)
print(f"IC 95% = [ {IC[0]:.4f} ; {IC[1]:.4f} ]")
print(f"IC 95% = [ {IC[0]:.2%} ; {IC[1]:.2%} ]")

IC 95% = [ 0.5123 ; 0.6877 ]
IC 95% = [ 51.23% ; 68.77% ]


2. Interpreta para el equipo docente: ¿cuál es el rango de aprobación estimado en todo el grupo de estudiantes?

**Podemos decir con un 95% de confianza, el interval de confianza poblacional se encuentra entre 51.23% y 68.77%**

**Si se dicta este curso y se vuelven a tomar muestras representativas, el 95% de las veces dará que el porcentaje de aprobación se encuentra entre 51.23% y 68.77%**

**En términos estadísticos para este tipo de asignaturas el peor de los casos la aprobación del curso será de 51.23% y en el mejor de los casos de 68.77%**

# **Actividad 3 — Satisfacción de clientes en compras online**

Una empresa de comercio electrónico está evaluando la calidad de su servicio al cliente. Para esto revisó 500 compras recientes, preguntando a los compradores si el servicio recibido fue “satisfactorio”. Entre ellos, 420 clientes respondieron afirmativamente. La empresa busca estimar, con un 90% de confianza, la proporción real de clientes satisfechos y comprender cómo cambiaría la precisión de la estimación si se aumentara el nivel de confianza a 99%.

1. ¿Cuál es el valor de la proporción muestral $ \hat{p}$?

In [32]:
n = 500
x = 420
p_muestra = x/n
print(p_muestra)

0.84


2. Estima e interpreta el intervalo de confianza al 90% para la proporción poblacional de clientes satisfechos.

In [39]:
alfa = 0.1

for alfa in [0.10, 0.01]:
    z = st.norm.ppf(1 - alfa/2)
    SE = np.sqrt(p_muestra * (1 - p_muestra) / n)
    IC = (p_muestra - z * SE, p_muestra + z * SE)
    print(f"IC {1 - alfa:.0%} = [ {IC[0]:.2%} ; {IC[1]:.2%} ]")

IC 90% = [ 81.30% ; 86.70% ]
IC 99% = [ 79.78% ; 88.22% ]


3. ¿Cómo cambia el tamaño del intervalo y la precisión de la estimación al aumentar el nivel de confianza del 90% al 99%?

**A mayor nivel de confianza, será más amplio el intervalo y menos precico en la estimacion**

## **Gráfico interactivo**

Utiliza el siguiente gráfico interactivo para explorar cómo cambia el intervalo de confianza al modificar el nivel de confianza, el tamaño muestral ($n$) y el valor de $x$.

Al mover los deslizadores, observa especialmente:
* Cómo varía el ancho del intervalo al cambiar el nivel de confianza,
* Qué ocurre con la precisión de la estimación.

*Indicación: Ejecuta la celda de código para visualizar el gráfico interactivo*


In [28]:
# @title
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
from ipywidgets import interact,  IntSlider, Dropdown, fixed

def viz_ic_proporcion_curva(x, n, confianza=0.95, titulo=None):
    # Evitar casos inválidos
    if x < 0 or x > n:
        return

    phat = x / n
    z = st.norm.ppf(1 - (1-confianza)/2)
    se = np.sqrt(phat*(1 - phat)/n)
    L, U = phat - z*se, phat + z*se

    # Rango para la curva normal aproximada
    xs = np.linspace(max(0, phat - 4*se), min(1, phat + 4*se), 800)
    ys = st.norm.pdf((xs - phat)/se) / se

    # Gráfico
    plt.figure(figsize=(7,4))
    plt.plot(xs, ys)

    # sombreado del intervalo de confianza
    mask = (xs >= L) & (xs <= U)
    plt.fill_between(xs, ys, where=mask, alpha=0.3)
    plt.axvline(phat, linestyle="--", linewidth=1)
    plt.axvline(L, linestyle="--", linewidth=1)
    plt.axvline(U, linestyle="--", linewidth=1)

    if titulo is None:
        titulo = f"IC {int(confianza*100)}% para p con aproximación normal"
    plt.title(titulo)
    plt.xlabel("Proporción")
    plt.ylabel("Densidad (aprox. normal)")
    plt.text(phat, max(ys)*0.9, f"$\\hat p$={phat:.3f}", ha="center")
    plt.text(L, max(ys)*0.6, f"L={L:.4f}", ha="center", rotation=90, va="center")
    plt.text(U, max(ys)*0.6, f"U={U:.4f}", ha="center", rotation=90, va="center")
    plt.tight_layout()
    plt.show()

# --- INTERACTIVIDAD (único agregado real) ---
interact(
    viz_ic_proporcion_curva,
    x=IntSlider(value=70, min=0, max=500, step=10, description='x'),
    n=IntSlider(value=200, min=20, max=500, step=10, description='n'),
    confianza=Dropdown(options=[0.90, 0.95, 0.99], value=0.90, description='Confianza'),
    titulo=fixed(None)
);


interactive(children=(IntSlider(value=70, description='x', max=500, step=10), IntSlider(value=200, description…

4. ¿Qué representa el nivel de confianza en un IC y cómo se interpreta en el contexto de este problema?

El nivel de confianza representa el grado de seguridad asociado al método utilizado para construir el intervalo de confianza.

En este problema, decir que el intervalo tiene un nivel de confianza del 90% o del 99% significa que, si se repitiera el procedimiento muchas veces con distintas muestras del mismo tamaño, aproximadamente el 90% o el 99% de los intervalos construidos contendrían la verdadera proporción poblacional.


# **Actividad 4 — Eficacia de un tratamiento en salud**

En un estudio piloto, se evaluó la eficacia de un tratamiento en un grupo de pacientes que presentan la misma condición médica.

La información recolectada se encuentra en la base de datos que puedes descargar **[aquí](https://docs.google.com/spreadsheets/d/14jQZkHA1M8iD4-q5KHAL5qydOEso7tCN/export?format=xlsx)**, la cual contiene el registro de cada paciente y si presentó o no mejoría tras el tratamiento.

En la variable mejora, el valor 1 indica que el paciente presentó mejoría, mientras que el valor 0 indica que no presentó mejoría.

Utiliza esta información para estimar la proporción poblacional de pacientes que presentan mejoría y analizar la incertidumbre asociada a dicha estimación.


1. Carga la base de datos y determina el tamaño de la muestra ($n$) y el número de pacientes que presentaron mejoría ($x$).

In [51]:
df = pd.read_excel('G3_A4_tratamiento_salud.xlsx')
n = len(df)
x = len(df[df['mejora'] == 1])

print(f'El tamaño de la muestra es {n} y el número de pacientes que presentaorn mejoría es {x}')

El tamaño de la muestra es 50 y el número de pacientes que presentaorn mejoría es 34


2. Calcula la proporción muestral $\hat{p}$ y construye un intervalo de confianza del 99 % para la proporción poblacional de pacientes que presentan mejoría.

In [56]:
p_muestra = x / n

alfa = 0.01
z = st.norm.ppf(1 - alfa/2)
SE = np.sqrt(p_muestra * (1 - p_muestra)/n)
IC = (p_muestra - z * SE, p_muestra + z * SE)
print(f"IC {1 - alfa:.0%} = [ {IC[0]:.2%} ; {IC[1]:.2%} ]")


IC 99% = [ 51.01% ; 84.99% ]


3. Interpreta los resultados obtenidos como si debieras reportarlo en un informe médico, explicando qué indica el rango estimado y cuán precisa es esta estimación.

**Con un 99% de confianza podemos decir que en el mejor escenario un 84.99% de pacientes mejorará, mientras que en el peor de los casos un 51.01% de los pacientes no mejoraría**

# **Actividad 5 — Análisis de opiniones en redes sociales**

Un equipo de analítica digital monitorea la percepción de un nuevo producto tecnológico a través de redes sociales. Para evaluar el impacto de la campaña de lanzamiento, se recopilaron tuits relacionados con el producto, identificando si el tono de cada mensaje es positivo o negativo.

El área de marketing se ha fijado como meta alcanzar al menos un 70% de opiniones positivas y quiere saber si los datos disponibles respaldan ese objetivo con un nivel de confianza del 95%.

Descarga la base de datos **[aquí](https://docs.google.com/spreadsheets/d/1kRZe090udX45FpcUwJYCHvebpBJu0X9q/export?format=xlsx)** y considera que, en la variable “es_positivo”, el valor 1 indica una opinión positiva y el valor 0 una opinión negativa.


1. Carga la base y determina el tamaño de la muestra ($n$) y la cantidad de opiniones positivas ($x$).

2. Calcula $\hat{p}$ y construye un IC del 95% de confianza para la proporción poblacional de opiniones positivas.

3. Concluye si, con 95% de confianza, el equipo de marketing ha alcanzado su meta.

# **Actividad 6 - Proporción de actitud positiva**

Se aplica un cuestionario que mide la actitud hacia la autoevaluación de la calidad educativa a una muestra aleatoria de alumnos de la Facultad de Ciencias Matemáticas. De un total de 364 alumnos, 247 evidencian actitud positiva hacia la autoevaluación.

Se solicita que estime la proporción de alumnos de esta Facultad con actitud positiva hacia la autoevaluación de la calidad educativa con un nivel de confianza del 90%.

# **Actividad 7 - Control de calidad con intervalos**

La Comisión de Salud pretende implantar un programa de ayuda a familias con familiares dependientes. El programa es financiado por un organismo público y ejecutado por los municipios.

Por errores inevitables, no todas las familias a las que se subvenciona cumplen los requisitos exigidos, pero el organismo supervisor del programa considera aceptable que esto ocurra en no más del 4% de los casos. Si se supera este porcentaje, el municipio será sancionado.

En un municipio se muestrean 200 familias y se detecta que 12 de ellas no cumplen las condiciones exigidas. Considerando un nivel de confianza del 90%, ¿debe sancionarse al municipio?


# **Actividad de cierre — Aplicación a tu contexto**

Imagina un escenario real de tu área profesional en el que necesites estimar una proporción relevante (ej.: porcentaje de clientes satisfechos, tasa de aprobación, proporción de fallas, etc.).

1.	Describe la proporción que deseas estimar y explica por qué sería útil conocerla en el contexto que imaginaste.

2.	Describe cómo obtendrías una muestra adecuada para estimar dicha proporción.
3.	Indica si se cumplirían las condiciones para utilizar la aproximación normal y justifica tu respuesta.

4.	Elige un nivel de confianza y explica tu decisión, considerando el equilibrio entre precisión de la estimación y nivel de seguridad.

5.	En el escenario que planteaste, reflexiona sobre cómo el tamaño de la muestra y el nivel de confianza influyen en la precisión del intervalo de confianza y en la toma de decisiones. ¿Qué podrías modificar para reducir el margen de error de tu estimación?


# **Con este laboratorio aprendiste a:**

*	Construir intervalos de confianza para proporciones y decidir cuándo la aproximación normal es válida.
*	Interpretar el efecto del tamaño muestral y del nivel de confianza sobre la precisión de la estimación.
*	Utilizar intervalos de confianza para respaldar decisiones basadas en metas o criterios de control.
*	Aplicar los conceptos de inferencia estadística a tu propio contexto profesional.
